include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    cancel_subscriptions: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    combinators_ordering: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
